sonar.organization=den1389
sonar.projectKey=den1389_library-management-system_ref
sonar.projectName=Library Management System
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.tests=tests
sonar.language=py
sonar.python.version=3.11

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=junit.xml

sonar.exclusions=**/__pycache__/**,**/*.pyc,docs/**
sonar.coverage.exclusions=tests/**,**/__init__.py

sonar.qualitygate.wait=true